Interstation-Two-WW2/code/game/objects/structures/curtains.dm

Ditto with #69 for #6 - this is supposed to apply changes from #13. Hopefully it should be working this time.

Anchored curtains (Re-PR)

---

Interstation-Two-WW2/code/modules/WW2/gun-bolt-action.dm

I noticed my fix, PR #6, wasn't properly merged with the code, hence I am opening this again.

Fixed clip ejection for boltactions (Re-PR)

---

Interstation-Two-WW2/code/modules/WW2/sandbags/cover.dm
Interstation-Two-WW2/code/modules/WW2/sandbags/sandbag.dm

Fixes: #92
Fixes sandbags becoming unanchored
Fixes sandbags being unidirectional
Fixes a fuckton of hacks and bad code
Fixes smoke not passing sandbags

Fixes all the bugs with sandbags

---

Interstation-Two-WW2/code/modules/projectiles/gun.dm

Big guns (w_class >= 4) Have a chance to stop melee attacks. If the gun has a bayonet on it then the chance is increased.
Resolves #107

Gives rifles a chance to stop melee attacks

---

Interstation-Two-WW2/code/game/objects/items.dm
Interstation-Two-WW2/code/modules/WW2/weapons/guns/stationary.dm
Interstation-Two-WW2/code/modules/mob/inventory.dm
Interstation-Two-WW2/code/modules/mob/use_object.dm

And added spaghetti a la bolognesa
Addresses #26 and #28

Fixed Maxim reloading and zooming

---

Interstation-Two-WW2/Interstation-Two-WW2.dme
Interstation-Two-WW2/code/modules/WW2/jobs/german.dm
Interstation-Two-WW2/code/modules/WW2/jobs/job_language.dm
Interstation-Two-WW2/code/modules/WW2/jobs/russian.dm

Addresses #77 and cleaned up the code to prevent similar issues in the future

Fixes #77 and makes language addition more uniform

---

Interstation-Two-WW2/code/modules/WW2/loudspeaker.dm

Fixes a mistake with the loudspeaker

---

Interstation-Two-WW2/code/game/objects/items/weapons/grenades/grenade.dm

limmits grenade throw range

---

Interstation-Two-WW2/code/game/objects/items/devices/binoculars.dm

Addresses an issue-less complainant in the general channel.
Please create issues next time.

Fixes binoculars being unusuable

---

Interstation-Two-WW2/code/modules/mob/mob_movement.dm

Fixes unintended zoom presistence when moving

---

Interstation-Two-WW2/Interstation-Two-WW2.dme
Interstation-Two-WW2/code/modules/WW2/items/health/doctor_handbook.dm
Interstation-Two-WW2/code/modules/WW2/jobs/german.dm
Interstation-Two-WW2/code/modules/WW2/jobs/russian.dm
Interstation-Two-WW2/code/modules/organs/wound.dm

Addressing #8.
What it does:
* Tells the user if the victim the book is used on is suffering toxin damage, blood loss, or malnourishment
* Gives descriptions on wounds, bruises, burns, and broken bones at each part of the body.
* It pronounces difference between alive and dead through flavor text.
* Currently does only work on humans
What is needed:
* Sprites
Other input is also appreciated.

Adds doctor's handbook

---

Interstation-Two-WW2/Interstation-Two-WW2.dme
Interstation-Two-WW2/code/modules/WW2/gun-bolt-action.dm
Interstation-Two-WW2/code/modules/WW2/weapons/attachment.dm
Interstation-Two-WW2/code/modules/WW2/weapons/zoom.dm

-Fixes Binocs  
-Balances aiming cooldown.  
-Better Player Messages
-Changes in some messages to make it a tad bit easier to understand
Oh and changing zoom is still unintuitive.

IMPORTANT HOTFIX

---

Interstation-Two-WW2/code/modules/WW2/tank/damage.dm
Interstation-Two-WW2/code/world.dm

fixes really bad damage bug that resulted in heals

---

Interstation-Two-WW2/code/modules/WW2/jobs/german.dm

Changes US army ranks into German abbreviated army ranks

Fixes german ranks

---

code/game/objects/items/weapons/storage/medkit.dm

Going to remove all space named shit.

QoLI: Med-Kit Names

---

code/processes/mapswap.dm

Need this so i can test out new map.

---

code/processes/mapswap.dm

Add POW to rotation

---

code/game/objects/map_metadata/camp.dm
code/game/objects/structures/underground.dm

Increased time for escapees to be recaptured.
Fixed the loop.
Decreased grace wall time for germans to 1 minute.
Increased underground blocks to 350.
Increased percentages of germans from 20% to 30%

More fixes

---

code/game/objects/map_metadata/camp.dm

Fixed loop at the end of round

---

code/modules/WW2/jobs/german.dm

Radios for everyone

---

code/game/objects/map_metadata/camp.dm

Minor fixes to camp

---

code/__defines/maps.dm

Revert "so survival works"

---

code/modules/WW2/weapons/grenades.dm

Might add other chem nades for different factions if this works well

Adds american smoke and PHOSPHORUS!!

---

code/game/objects/map_metadata/_map_metadata.dm
code/game/objects/map_metadata/occupation.dm
code/modules/WW2/jobs/civilian.dm

Now civ player can be spawned as a partisan with a 20% chance. Up to 4 partisans in the round.

Partisan spawner

---

code/modules/WW2/letter.dm

Letter now picks a random drop point and tells player where he can find that drop point.

Partisan shop improvment

---

code/datums/hud.dm
code/game/objects/items/weapons/storage/storage.dm
code/modules/reagents/reagent_containers/spray.dm

Backpack contents now being showed up correctly. http://puu.sh/BcYgI/7e7072f30c.jpg
Also replacing plantbgone sprayer contents with existing reagents (polytrinic acid)

Backpack hud fix

---

code/game/objects/structures/key_doors/keychain.dm
code/modules/WW2/trench.dm

- Removed delay after removing a key from a keychain.
- Fixed trenches.

Keychain Fix + Trench Fix

---

code/game/turfs/floor_attackby.dm
code/game/turfs/flooring/flooring_premade.dm
code/modules/WW2/tools.dm
code/modules/WW2/trench.dm

Press Z to collect dirt and attack a tile to build a trench.

changes trench and dirt extraction

---

code/game/objects/structures/wild.dm

Revert "Edd updates"

---

code/modules/WW2/apparel.dm
code/modules/WW2/jobs/german.dm
code/modules/WW2/jobs/japanese.dm
code/modules/WW2/jobs/soviet.dm
code/modules/WW2/jobs/usa.dm
code/modules/WW2/vending.dm

Revert "ghillie suit snipers"

---

code/game/objects/items/clothing/suits/misc.dm
code/game/objects/items/paper/carbon.dm
code/game/turfs/turf.dm
code/modules/admin/admin_secrets.dm
code/modules/organs/organ_external.dm

These errors break the renderer completely

Makes us webmap-compatible

---

code/modules/WW2/jobs/german.dm
code/modules/WW2/jobs/italian.dm
code/modules/WW2/jobs/japanese.dm
code/modules/WW2/jobs/soviet.dm
code/modules/WW2/jobs/usa.dm
code/modules/mob/grab.dm

_Two in one, woooweeee what a deal!_
Medical stats for medics have been raised to be equal with doctors because people want them to you know.. _Actually heal people and not yell at them to go find a doctor._ 
Fixes the Grab List bug the server has been having. Changes two words to = null. _I'm tired of the ahelps about it._

Medics can actually heal + Grab list fix. 
